### ISSUE TITLE
Sysgrep command incorrect

### ISSUE THREAD

**Issue by dobharweim** [ibm-cloud-docs/image-templates#15]
The final sysgrep command on page https://github.com/ibm-cloud-docs/image-templates/blob/5be5f63bba214acd71100eb5403f403252c4a462/image_cloud-init.md

is failing for me. I moved the unattend file to C:\ and ran "C:\Windows\System32\Sysprep\sysprep.exe /generalize /oobe /shutdown /unattend:C:\Unattend.xml" instead.

**Comment by amatetic** [comment]
thank you for your feedback - we will be looking at your feedback in an upcoming sprint

**Comment by amatetic** [comment]
@dobharweim I have reviewed the content with development and the code example is now updated. Please let us know if this resolves the issue: https://cloud.ibm.com/docs/image-templates?topic=image-templates-provisioning-with-a-cloud-init-enabled-image#windows-requirements
