### ISSUE TITLE
Missing Ubuntu 20 as a support image for import

### ISSUE THREAD

**Issue by tommyk-enablement** [ibm-cloud-docs/image-templates#16]
Confirmed with dev that Ubuntu 20 is supported and should be included in the doc as a support image import version. 

https://cloud.ibm.com/apidocs/vpc#list-operating-systems
would list the supported images as another means of determining what can be imported.

**Comment by gudrun-wolfgram** [comment]
@tommyk-enablement - this image-templates content is for classic infrastructure. 

The list of supported images for VPC is available here: VPC stock images topic: https://cloud.ibm.com/docs/vpc?topic=vpc-about-images

**Comment by gudrun-wolfgram** [comment]
Thanks for the feedback @tommyk-enablement . This issue has been addressed.
