### ISSUE TITLE
ISO mount - boot from image caveats

### ISSUE THREAD

**Issue by gaskinner84** [ibm-cloud-docs/image-templates#18]
Hello all,

I am looking to add some information to this section of documentation. https://cloud.ibm.com/docs/image-templates?topic=image-templates-booting-a-vsi-from-an-image

Recently, Veeam customers who create Windows DISM ISOs are running into an issue:

1) Customer mounts ISO(boot from image in VSI UI)
2) Customer is not able to catch the "press any key" prompt to boot the ISO
3) Since there is no interaction, the machine boots the native OS disk 

Support has learned that DISM created ISOs have a "press any key" prompt which require intervention at the KVM for the ISO to be booted. If the customer does not press "any key" within 5 seconds, the VSI will boot the normal OS, bypassing the ISO. 

This is confusing to many customers, as they are not able to login to the KVM in time to see this "press any key prompt" and deem the ISO bad, or say something is wrong with our platform when the ISO does not boot when in actuality, they are not pressing "any key" when prompted. 

In my opinion, we need a caveat here to describe this behavior. 

Something like: Customers, please keep in mind, DISM created ISOs will have a "press any key to boot from CD" that requires action via the KVM to boot the ISO. If the "press any key" cannot be interacted with because of the time it takes to connect to the KVM, we recommend editing the ISO to remove the "press any key" prompt. Removing the prompt will ensure the ISO boots without interaction. 

The prompt can be removed from an DISM created ISO by: 

1)open the ISO it with a capable ISO editting app. IE: PowerISO, UltraISO, etc
2)delete bootfix.bin 
3)replace EFISYS.BIN with efisys_noprompt.bin.
4)Then save the ISO.

efisys_noprompt.bin can be found on most Windows installs by searching.

Regards,

Gary S.
ACS-Storage Support Lead
IBM Cloud Support

**Comment by gudrun-wolfgram** [comment]
A jira issue has been created to track and implement this update.

**Comment by gudrun-wolfgram** [comment]
@gaskinner84 - I've added the following troubleshooting topic for your review. Please let me know if it is accurate and complete. 

Why won't my Windows DISM created ISO image boot?
https://test.cloud.ibm.com/docs/image-templates?topic=image-templates-troubleshoot-dism-boot

**Comment by gudrun-wolfgram** [comment]
@gaskinner84 - the new topic is published here:

Why won't my Windows DISM created ISO image boot?
https://cloud.ibm.com/docs/image-templates?topic=image-templates-troubleshoot-dism-boot

This update resolves the related jira item:

Create TBS topic for boot from Windows DISM ISO
https://jiracloud.swg.usma.ibm.com:8443/browse/CFD-6446
